spring:
  mvc:
    dispatch-options-request: true
  jpa:
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
        generate_statistics: false
        jdbc:
          batch_size: 50
          fetch_size: 50
        order_updates: true
        order_insert: true
    open-in-view: true
    show-sql: true
    hibernate:
      ddl-auto: create

#  sql:
#    init:
#      platform: postgresql
#      mode: embedded
#      encoding: utf-8

  datasource:
    url: jdbc:h2:mem:schoolData
    username: sa
    password: password
    driver-class-name: org.h2.Driver
